= JSON Schema Reference Resolver
:icons: font


image:https://img.shields.io/github/release/EuPathDB-Infra/js-deref.svg?style=flat-square[GitHub tag,link=https://github.com/EuPathDB-Infra/js-deref/releases/latest]
image:https://img.shields.io/travis/EuPathDB-Infra/js-deref/master.svg?style=flat-square[Travis (.org) branch,link=https://travis-ci.org/EuPathDB-Infra/js-deref]

Recursively resolves `"$ref"` properties and appends the
external schema content to the root `"definitions"` object.

If an output directory is provided, the tool writes the
dereferenced json files to the output directory, mirroring
the structure of the input directory.

If no output directory is provided, the tool simply performs
the validation checks.

WARNING: This utility is not presently suited for general
use as a json schema ref resolver.  It is tailored to the
specific case of absolute filesystem path references to the
root of a java project's resource directory.

== Usage

[source, bash session]
----
$ js-deref <input_dir> [output_dir]
----

== Rule checks

Out of the rules established for the JSON Schema files in
the WDK, the following are enforced by js-deref:

Out of Scope / Missing:: A JSON Schema file is referenced
  which is not present in the resources directory.

Absolute Refs:: All references must be "absolute" to the
  root of the resources directory.  (These paths will become
  absolute paths in the compiled WDK jar).
